### PR TITLE
update README, add Testing with 3rd

### PR DESCRIPTION
**Pull request by Eideen**
I wanted to test with a different, so i know it is working, with other tools.
It is probably others that like to do the same. 

great tool you have made @troglobit !

### CODE REVIEW

**Comment by troglobit** [comment]
Thanks for the kind words.

However, I'm not so sure I want to add your patch to the project.  I'd rather recommend ppl use mcjoin as both sender and receiver.  Maybe your example is better suited in `doc/INTEROP` or sth like that?

**Comment by Eideen** [comment]
I fully understand your view. 

For me it was imported to understand how multicast work, and that on the sender side, you only need to proved the multicast address, and it is not some other magic that is done. (You might be a wizard, Harry! :P ) And on the server side it is the application that controllers join and leave of multicast groups.
So you are correct that this not the use case `mcjoin` is build for, since `mcjoin` more of a `iperf3` similar tool. So to test my hypothesis, the use of `logger`, was a simple way.

https://access.redhat.com/solutions/110013
"The add and remove of the multicast address is controlled by the application which will listen for the multicast traffic."

**Output with  `logger` as client:** 
````
                                   mcjoin :: receiving multicast                                2m 32s
server (192.168.0.8@bridge0)          [Help | Toggle | Quit]                 Fri Jan 15 17:14:55 2021
Source,Group   Plotter                                                                         Packets
*,225.1.2.3  | [   I    I    I    I    I    I    I    I    I    I    I    I    I     I    I ]      117

Time                      Log                                                                         
Fri Jan 15 17:12:23 2021  Joining (*,225.1.2.3) on bridge0, ifindex: 6, sd: 9
````

**Comment by troglobit** [comment]
It's a good example.  There's also the (relatively new) `autojoin` feature of iproute2 that I believe was added for VXLAN. Just FYI.

I'm happy to merge the PR if you move the info to another file in doc/, as I mentioned.  You can just force-push to your branch, if you want.

**Comment by troglobit** [comment]
Looking good, merging this now :-)

**Comment by troglobit** [comment]
Thank you!

**Pull request merged**
