### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ceclinux**

### CODE REVIEW

**Comment by RomanIOPSYS** [comment]
Shouldn't it say `every MSEC milliseconds`?

**Comment by Forst** [comment]
Shouldn't it say `every MSEC milliseconds`?

**Comment by troglobit** [comment]
Admittedly, I'm not a native English speaker but I agree with @Forst so could you please update your PR accordingly, @ceclinux ?

**Comment by troglobit** [comment]
Second thought, I'm merging and fixing this up myself -- quicker turnaround for everyone :)

**Comment by troglobit** [comment]
Also updated src/mcjoin.c, which imo is more important.

**Comment by troglobit** [comment]
OMG, I really can't spell!  But at least I'm consistent, the same spelling error also in mcjoin.c and mcjoin.1 (man page) LOL

**Comment by ceclinux** [comment]
Not a native speaker as well. https://www.quora.com/Which-one-is-correct-every-second-or-every-one-second-or-every-a-second every second is correct so I think it should be every millisecond

**Comment by Forst** [comment]
The meaning is usually "every N seconds", because N is most likely plural/a number greater than one.

There are two ways to go about it:

* Every N seconds
* Every Nth second

Both are possible, but the first one is more frequently used from my experience.

**Comment by troglobit** [comment]
I agree with @Forst the "every N seconds" is the most common.   I've changed it consistently (finally) in all three locations now.  Thank you so much for your input in this! :heart:

**Pull request merged**
